const games = [
{ name:"Gates Of Olympus 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympx.png", rtp:85 },
{ name:"Gates Of Olympus Super Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympgold.webp", rtp:79 },
{ name:"Fortune Of Olympus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympgcl.webp", rtp:81 },
{ name:"Starlight Princess Super Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20starprss.webp", rtp:85 },
{ name:"Mahjong Wins 3 - Black Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmahwblck.webp", rtp:26 },
{ name:"Gates Of Gatot Kaca Super Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olgatssc.webp", rtp:15 },
{ name:"Starlight Princess 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20starlightx.png", rtp:33 },
{ name:"Sweet Bonanza 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fruitswx.webp", rtp:41 },
{ name:"Gates Of Olympus", img:"https://images.linkcdn.cloud/global/game-favorit/populer/vs20olympgate.webp", rtp:55 },
{ name:"Wisdom Of Athena 1000 Xmas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20procountxm.webp", rtp:67 },
{ name:"Mahjong Wins 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmahwin2.webp", rtp:93 },
{ name:"Gates Of Gatot Kaca 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gatotx.png", rtp:85 },
{ name:"Starlight Archer 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20stararx.webp", rtp:79 },
{ name:"Starlight Princess", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20starlight.png", rtp:81 },
{ name:"Sugar Rush 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugarrushx.png", rtp:85 },
{ name:"Sweet Bonanza Super Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20swbonsup.webp", rtp:26 },
{ name:"Gates Of Olympus Xmas 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympxmas.webp", rtp:15 },
{ name:"Sweet Rush Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20swrbon.webp", rtp:33 },
{ name:"Gates Of Pyroth", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20shmnarise.webp", rtp:41 },
{ name:"Wrath Of Nezha", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40wrathnez.webp", rtp:55 },
{ name:"Mahjong Wins – Gong Xi Fa Cai", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmahwgong.webp", rtp:67 },
{ name:"Aztec Gems", img:"https://images.linkcdn.cloud/global/popular-games/vs5aztecgems.webp", rtp:93 },
{ name:"Rujak Bonanza™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rujakbnz.png", rtp:85 },
{ name:"Sweet Bonanza Xmas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sbxmas.png", rtp:79 },
{ name:"Wild West Gold Blazing Bounty", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wwgcluster.webp", rtp:81 },
{ name:"Sweet Bonanza", img:"https://images.linkcdn.cloud/global/popular-games/vs20fruitsw.webp", rtp:85 },
{ name:"Wisdom Of Athena 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20procountx.webp", rtp:26 },
{ name:"Gates Of Gatot Kaca", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gatotgates.png", rtp:15 },
{ name:"Fortune Ace Super Scatter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfortsup.webp", rtp:33 },
{ name:"Plinko+", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/ar10plinko.webp", rtp:41 },
{ name:"Pyramid Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20pbonanza.png", rtp:55 },
{ name:"Bonanza Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bonzgold.png", rtp:67 },
{ name:"Mahjong Wins Bonus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024mjwinbns.png", rtp:93 },
{ name:"Wild West Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40wildwest.png", rtp:85 },
{ name:"Sweet Bonanza 1000 Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20swdicex.webp", rtp:79 },
{ name:"Sugar Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugarrush.png", rtp:81 },
{ name:"5 Lions Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayslions.png", rtp:85 },
{ name:"Triple Pot Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysasiatrzn.webp", rtp:26 },
{ name:"Gates Of Olympus 1000 Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20dicegatex.webp", rtp:15 },
{ name:"Gates Of Hades", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gtsofhades.webp", rtp:33 },
{ name:"Mahjong Wins™", img:"https://images.linkcdn.cloud/global/game-favorit/populer/vs1024mahjwins.webp", rtp:41 },
{ name:"Wisdom Of Athena", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20procount.png", rtp:55 },
{ name:"Gates Of Olympus Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympdice.png", rtp:67 },
{ name:"Great Rhino Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysrhino.png", rtp:93 },
{ name:"Joker & s Jewels", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5joker.png", rtp:85 },
{ name:"Candy Village", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20candvil.png", rtp:79 },
{ name:"Aztec Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7776aztec.png", rtp:81 },
{ name:"Resurrecting Riches", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysresurich.webp", rtp:85 },
{ name:"Waves Of Poseidon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bigmass.webp", rtp:26 },
{ name:"5 Lions Megaways 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vsways5lions2.webp", rtp:15 },
{ name:"Starlight Christmas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20schristmas.png", rtp:33 },
{ name:"Aztec Gems Deluxe", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9aztecgemsdx.png", rtp:41 },
{ name:"Sleeping Dragon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25sleepdrag.webp", rtp:55 },
{ name:"Power Of Thor Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayshammthor.png", rtp:67 },
{ name:"Vampy Party", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswbounty.webp", rtp:93 },
{ name:"Bandit Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbandit.webp", rtp:85 },
{ name:"Zeus Vs Hades - Gods Of War", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15godsofwar.png", rtp:79 },
{ name:"Aztec Gems Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysaztec.webp", rtp:81 },
{ name:"Sweet Bonanza Dice™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bnnzdice.png", rtp:85 },
{ name:"Sugar Supreme Powernudge™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugarnudge.png", rtp:26 },
{ name:"Gates Of Aztec", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20aztecgates.png", rtp:15 },
{ name:"Big Bass Bonanza 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbbnz1000.webp", rtp:33 },
{ name:"Mummy’s Jewels", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmjwl.webp", rtp:41 },
{ name:"Power Of Ninja", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20ninjapower.png", rtp:55 },
{ name:"Chests Of Cai Shen", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25checaishen.webp", rtp:67 },
{ name:"Candy Blitz Bombs", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20candybltz2.webp", rtp:93 },
{ name:"5 Rabbits Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysrabbits.png", rtp:85 },
{ name:"Sugar Rush Xmas™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugrux.png", rtp:79 },
{ name:"Fiesta Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10gbseries.webp", rtp:81 },
{ name:"Buffalo King Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbufking.png", rtp:85 },
{ name:"5 Lions Reborn", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vsways5lionsr.webp", rtp:26 },
{ name:"Madame Destiny Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmadame.png", rtp:15 },
{ name:"Santa & s Great Gifts", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20porbs.png", rtp:33 },
{ name:"Fruit Party", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fruitparty.png", rtp:41 },
{ name:"Cash Surge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscashsurg.webp", rtp:55 },
{ name:"Lucky Lightning", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayslight.png", rtp:67 },
{ name:"Fire Portals", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20portals.png", rtp:93 },
{ name:"Witch Heart Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswildbrst.webp", rtp:85 },
{ name:"Wild West Gold Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswildwest.png", rtp:79 },
{ name:"Fire Strike", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10firestrike.png", rtp:81 },
{ name:"The Dog House Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysdogs.png", rtp:85 },
{ name:"Candy Blitz™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20candyblitz.png", rtp:26 },
{ name:"The Dog House", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20doghouse.png", rtp:15 },
{ name:"Majestic Express – Gold Run", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25goldrexp.webp", rtp:33 },
{ name:"Gems Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20goldfever.png", rtp:41 },
{ name:"John Hunter - The Scarab Queen", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25scarabqueen.png", rtp:55 },
{ name:"Gold Party 2 – After Hours", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25goldpartya.webp", rtp:67 },
{ name:"Christmas Carol Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20xmascarol.png", rtp:93 },
{ name:"Extra Juicy Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysxjuicy.png", rtp:85 },
{ name:"Joker’s Jewels Cash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5jokerjc.webp", rtp:79 },
{ name:"Wukong Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mkrush.png", rtp:81 },
{ name:"Rabbit Garden", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20goldclust.png", rtp:85 },
{ name:"Gem Fire Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gemfirefor.webp", rtp:26 },
{ name:"Big Bass Boxing Bonus Round", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbbbrnd.webp", rtp:15 },
{ name:"Fruity Treats", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fortbon.jpg", rtp:33 },
{ name:"Fire Stampede™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysstampede.png", rtp:41 },
{ name:"Panda & s Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25pandagold.png", rtp:55 },
{ name:"Forge Of Olympus™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20forge.png", rtp:67 },
{ name:"Eye Of Spartacus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15eyeofspart.webp", rtp:93 },
{ name:"Kingdom Of Asgard", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20asgard.png", rtp:85 },
{ name:"7 Clovers Of Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayssevenc.webp", rtp:79 },
{ name:"Grace Of Ebisu™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20olympgrace.png", rtp:81 },
{ name:"Mining Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20minerush.webp", rtp:85 },
{ name:"888 Dragons", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1dragon8.png", rtp:26 },
{ name:"Gem Trio", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9gemtrio.webp", rtp:15 },
{ name:"Hot Fiesta", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25hotfiesta.png", rtp:33 },
{ name:"Cowboy Coins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysultrcoin.png", rtp:41 },
{ name:"Muertos Multiplier Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20muertos.png", rtp:55 },
{ name:"5 Lions", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243lions.png", rtp:67 },
{ name:"Mahjong Panda", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024mahjpanda.png", rtp:93 },
{ name:"Mustang Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25mustang.png", rtp:85 },
{ name:"Mochimon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mochimon.png", rtp:79 },
{ name:"Mustang Gold Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysgoldcol.webp", rtp:81 },
{ name:"Santa & s Wonderland", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20santawonder.png", rtp:85 },
{ name:"The Tweety House", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20tweethouse.png", rtp:26 },
{ name:"Power Of Merlin Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayspowzeus.png", rtp:15 },
{ name:"Temple Guardians", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10diamondrgh.webp", rtp:33 },
{ name:"Fortune Ace", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024fortune.png", rtp:41 },
{ name:"The Dog House - Dog Or Alive", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20doghouse2.webp", rtp:55 },
{ name:"The Dog House - Muttley Crew", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20dhcluster2.webp", rtp:67 },
{ name:"Twilight Princess™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20dhcluster.png", rtp:93 },
{ name:"Fortune Of Giza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20amuleteg.png", rtp:85 },
{ name:"Cyber Heist", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20cbrhst.png", rtp:79 },
{ name:"Mammoth Gold Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mammoth.png", rtp:81 },
{ name:"Brick House Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbrickhos.webp", rtp:85 },
{ name:"Pompeii Megareels Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmegareel.png", rtp:26 },
{ name:"Finger Lick’n Free Spins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fingerlfs.webp", rtp:15 },
{ name:"6 Jokers", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5magicdoor.webp", rtp:33 },
{ name:"Big Bass Vegas Double Down Deluxe", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbdoubled.webp", rtp:41 },
{ name:"888 Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5triple8gold.webp", rtp:55 },
{ name:"Money Roll", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/cs5moneyroll.png", rtp:67 },
{ name:"Bigger Bass Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs12bbb.png", rtp:93 },
{ name:"Christmas Big Bass Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bxmasbnza.png", rtp:85 },
{ name:"Chilli Heat Spicy Spins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10chillihmr.webp", rtp:79 },
{ name:"Viking Forge™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugarcoins.png", rtp:81 },
{ name:"Wild Wild Riches Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswwriches.png", rtp:85 },
{ name:"Clover Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mustanggld2.png", rtp:26 },
{ name:"Tiny Toads", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50fatfrogs.webp", rtp:15 },
{ name:"Wild West Duels", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20pistols.png", rtp:33 },
{ name:"Club Tropicana – Happy Hour", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs12trpcnhour.webp", rtp:41 },
{ name:"Book Of Monsters", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fatbook.webp", rtp:55 },
{ name:"The Hand Of Midas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20midas.png", rtp:67 },
{ name:"Santa & s Xmas Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rainbowrsh.webp", rtp:93 },
{ name:"Lucky’s Wild Pub", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25luckwildpb.webp", rtp:85 },
{ name:"5 Lions Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243lionsgold.png", rtp:79 },
{ name:"The Dog House Multihold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20doghousemh.png", rtp:81 },
{ name:"Candy Jar Clusters™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20cjcluster.png", rtp:85 },
{ name:"Sword Of Ares", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20swordofares.png", rtp:26 },
{ name:"Wild Wild Riches", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs576treasures.png", rtp:15 },
{ name:"Amazing Money Machine", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10amm.png", rtp:33 },
{ name:"Diamond Strike", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15diamond.png", rtp:41 },
{ name:"Big Bass Floats My Boat", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbfloats.png", rtp:55 },
{ name:"Fortunes Of Aztec™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysstrlght.png", rtp:67 },
{ name:"Hot Pepper", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20dugems.png", rtp:93 },
{ name:"Rise Of Samurai Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayssamurai.png", rtp:85 },
{ name:"Cowboys Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10cowgold.png", rtp:79 },
{ name:"Elemental Gems Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayselements.png", rtp:81 },
{ name:"Dragon Gold 88", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10dgold88.webp", rtp:85 },
{ name:"Joker’s Jewels Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5jjwild.jpg", rtp:26 },
{ name:"Big Bass Bonanza 3 Reeler", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5bb3reeler.webp", rtp:15 },
{ name:"Alien Invaders", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20alieninv.webp", rtp:33 },
{ name:"Treasure Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20trsbox.png", rtp:41 },
{ name:"Juicy Fruits", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50juicyfr.png", rtp:55 },
{ name:"Blitz Super Wheel", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lightblitz.webp", rtp:67 },
{ name:"Great Rhino Deluxe", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rhinoluxe.png", rtp:93 },
{ name:"Floating Dragon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10floatdrg.png", rtp:85 },
{ name:"Fruit Party 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fparty2.png", rtp:79 },
{ name:"The Wild Gang", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswildgang.webp", rtp:81 },
{ name:"Gold Party", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25goldparty.png", rtp:85 },
{ name:"5 Lions Dance", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024lionsd.png", rtp:26 },
{ name:"Buffalo King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs4096bufking.png", rtp:15 },
{ name:"Rise Of Samurai 3", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40samurai3.png", rtp:33 },
{ name:"Big Bass Secrets Of The Golden Lake<", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bblotgl.webp", rtp:41 },
{ name:"Jumbo Safari", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20jjjack.webp", rtp:55 },
{ name:"Big Bass Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbbonanza.png", rtp:67 },
{ name:"Cleocatra", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20cleocatra.png", rtp:93 },
{ name:"Bow Of Artemis", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gembondx.webp", rtp:85 },
{ name:"Super X", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20superx.png", rtp:79 },
{ name:"8 Dragons", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20eightdragons.png", rtp:81 },
{ name:"Ride The Lightning", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9ridelightng.webp", rtp:85 },
{ name:"Emperor Caishen", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243empcaishen.png", rtp:26 },
{ name:"Panda & s Fortune 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25pandatemple.png", rtp:15 },
{ name:"Monster Superlanche", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20superlanche.png", rtp:33 },
{ name:"Big Bass Splash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10txbigbass.png", rtp:41 },
{ name:"The Magic Cauldron - Enchanted Brew<", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20magicpot.png", rtp:55 },
{ name:"Cash Patrol", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25copsrobbers.png", rtp:67 },
{ name:"Rocket Blast Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysrockblst.png", rtp:93 },
{ name:"Floating Dragon Year Of The Snake", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fdsnake.webp", rtp:85 },
{ name:"Heart Of Rio", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25rio.png", rtp:79 },
{ name:"The Dog House Dice Show™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20dhdice.png", rtp:81 },
{ name:"Wild Bison Charge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20stickywild.png", rtp:85 },
{ name:"Rise Of Samurai 4", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15samurai4.jpg", rtp:26 },
{ name:"Raging Waterfall Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmltchmgw.webp", rtp:15 },
{ name:"Phoenix Forge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20phoenixf.png", rtp:33 },
{ name:"Bounty Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25btygold.png", rtp:41 },
{ name:"Bigger Bass Blizzard - Christmas Cat", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs12bbbxmas.png", rtp:55 },
{ name:"Fortune Dragon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243fdragon.png", rtp:67 },
{ name:"Starlight Princess Pachi", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysjapan.webp", rtp:93 },
{ name:"Money Money Money", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1money.png", rtp:85 },
{ name:"Extra Juicy", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fruity2.png", rtp:79 },
{ name:"Heart Of Cleopatra", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20heartcleo.jpg", rtp:81 },
{ name:"Hand Of Midas 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20midas2.png", rtp:85 },
{ name:"Wild Wildebeest Wins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbufstamp.webp", rtp:26 },
{ name:"Gods Of Giza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10gizagods.png", rtp:15 },
{ name:"Ultra Hold And Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5ultra.png", rtp:33 },
{ name:"Fire 88", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7fire88.png", rtp:41 },
{ name:"Samurai Code", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs12scode.webp", rtp:55 },
{ name:"Cosmic Cash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40cosmiccash.png", rtp:67 },
{ name:"Sweet Powernudge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20clspwrndg.png", rtp:93 },
{ name:"Fruit Party Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fpartydice.webp", rtp:85 },
{ name:"Golden Pig", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25goldpig.png", rtp:79 },
{ name:"Volcano Goddess", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysvlcgds.webp", rtp:81 },
{ name:"Club Tropicana", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs12tropicana.png", rtp:85 },
{ name:"Caishen & s Cash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243caishien.png", rtp:26 },
{ name:"Anime Mecha Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysanime.webp", rtp:15 },
{ name:"Sweet Kingdom", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20clustcol.webp", rtp:33 },
{ name:"Sticky Bees", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20clustwild.png", rtp:41 },
{ name:"Angel Vs Sinner", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15fghtmultlv.webp", rtp:55 },
{ name:"Dragon Hero", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20drgbless.png", rtp:67 },
{ name:"Chilli Heat", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25chilli.png", rtp:93 },
{ name:"Release The Kraken Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayskrakenmw.png", rtp:85 },
{ name:"Crystal Caverns Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscryscav.png", rtp:79 },
{ name:"Firebird Spirit - Connect & Coll", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysconcoll.png", rtp:81 },
{ name:"Big Bass Halloween™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bhallbnza.png", rtp:85 },
{ name:"Aztec Powernudge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sbpnudge.png", rtp:26 },
{ name:"Vegas Magic", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20vegasmagic.png", rtp:15 },
{ name:"Reel Banks", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25rlbank.png", rtp:33 },
{ name:"Old Gold Miner Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysoldminer.png", rtp:41 },
{ name:"Pizza! Pizza? Pizza!", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayspizza.png", rtp:55 },
{ name:"Greek Gods", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243fortseren.png", rtp:67 },
{ name:"Master Chen & s Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9chen.png", rtp:93 },
{ name:"Money Mouse", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25mmouse.png", rtp:85 },
{ name:"Rise Of Giza Powernudge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10nudgeit.png", rtp:79 },
{ name:"Coffee Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10coffee.png", rtp:81 },
{ name:"Dragon Kingdom", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25dragonkingdom.png", rtp:85 },
{ name:"Big Bass Amazon Xtreme", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbextreme.png", rtp:26 },
{ name:"Big Bass Christmas Bash™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbsplxmas.png", rtp:15 },
{ name:"Triple Tigers", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1tigers.png", rtp:33 },
{ name:"Wolf Gold Ultimate", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25ultwolgol.webp", rtp:41 },
{ name:"Bermuda Riches", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bermuda.png", rtp:55 },
{ name:"Might Of Freya Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmfreya.webp", rtp:67 },
{ name:"Big Bass Bonanza Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbbb.png", rtp:93 },
{ name:"Great Rhino", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rhino.png", rtp:85 },
{ name:"Big Bass - Hold & Spinner", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbhas.png", rtp:79 },
{ name:"Release The Kraken 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20kraken2.png", rtp:81 },
{ name:"Savannah Legend", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayssavlgnd.webp", rtp:85 },
{ name:"Candy Corner", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fourmc.webp", rtp:26 },
{ name:"Sumo Supreme Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmegwghts.webp", rtp:15 },
{ name:"Floating Dragon - Dragon Boat Festiv", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fdrasbf.png", rtp:33 },
{ name:"Buffalo King Untamed Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbkingasc.jpg", rtp:41 },
{ name:"Temujin Treasures", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024temuj.png", rtp:55 },
{ name:"Joker’s Jewels Hot", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10jokerhot.webp", rtp:67 },
{ name:"Jewel Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20jewelparty.png", rtp:93 },
{ name:"The Big Dawgs", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bigdawgs.png", rtp:85 },
{ name:"Master Joker", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1masterjoker.png", rtp:79 },
{ name:"Eternal Empress - Freeze Time", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfreezet.webp", rtp:81 },
{ name:"Bubble Pop", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bblpop.png", rtp:85 },
{ name:"Monkey Warrior", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243mwarrior.png", rtp:26 },
{ name:"Release The Kraken", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20kraken.png", rtp:15 },
{ name:"Wheel O’gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20multiup.png", rtp:33 },
{ name:"Drago - Jewels Of Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1600drago.png", rtp:41 },
{ name:"Big Bass Mission Fishin’", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbfmission.png", rtp:55 },
{ name:"Fruits Of The Amazon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20framazon.png", rtp:67 },
{ name:"Golden Ox", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25gldox.png", rtp:93 },
{ name:"Pyramid King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25pyramid.png", rtp:85 },
{ name:"Big Bass Bonanza - Keeping It Reel</", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbkir.png", rtp:79 },
{ name:"Tiger Treasures", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25tigeryear.png", rtp:81 },
{ name:"You Can Piggy Bank On It", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10piggybank.png", rtp:85 },
{ name:"Greedy Fortune Pig", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fortnpig.webp", rtp:26 },
{ name:"Aztec Smash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20plsmcannon.webp", rtp:15 },
{ name:"Fire Strike 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10firestrike2.png", rtp:33 },
{ name:"Money Stacks Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbblitz.webp", rtp:41 },
{ name:"Blazing Wilds Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfirewmw.png", rtp:55 },
{ name:"Money Stacks", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bblitz.webp", rtp:67 },
{ name:"Wild Celebrity Bus Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysrsm.png", rtp:93 },
{ name:"Wildies", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25wildies.webp", rtp:85 },
{ name:"Gatot Kaca & s Fury", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gatotfury.png", rtp:79 },
{ name:"Rock Vegas Mega Hold & Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rockvegas.png", rtp:81 },
{ name:"Mustang Trail™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10trail.png", rtp:85 },
{ name:"Tropical Tiki", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysjkrdrop.png", rtp:26 },
{ name:"Octobeer Fortunes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20octobeer.png", rtp:15 },
{ name:"Heist For The Golden Nuggets", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20hstgldngt.png", rtp:33 },
{ name:"Goblin Heist Powernudge", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gobnudge.png", rtp:41 },
{ name:"Moleionaire", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20clreacts.webp", rtp:55 },
{ name:"Wildman Super Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wildman.png", rtp:67 },
{ name:"3 Buzzing Wilds", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wildparty.png", rtp:93 },
{ name:"Gates Of Valhalla", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10runes.png", rtp:85 },
{ name:"Chicken Drop", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20chickdrop.png", rtp:79 },
{ name:"Wild Spells", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25wildspells.png", rtp:81 },
{ name:"Revenge Of Loki Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysloki.webp", rtp:85 },
{ name:"Pirate Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40pirate.png", rtp:26 },
{ name:"Hot To Burn Hold And Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20hburnhs.png", rtp:15 },
{ name:"5 Frozen Charms Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscharms.png", rtp:33 },
{ name:"Big Bass Xmas Xtreme", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbxext.png", rtp:41 },
{ name:"Barn Festival", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20farmfest.png", rtp:55 },
{ name:"Rise Of Pyramids", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayshexhaus.jpg", rtp:67 },
{ name:"Trees Of Treasure", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20treesot.png", rtp:93 },
{ name:"Big Bass Bonanza - Reel Action", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbbrlact.jpg", rtp:85 },
{ name:"Aztec Blaze", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25kfruit.png", rtp:79 },
{ name:"Juicy Fruits Multihold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50jfmulthold.webp", rtp:81 },
{ name:"Aztec Treasure Hunt", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20trswild3.webp", rtp:85 },
{ name:"3 Dancing Monkeys", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmonkey.png", rtp:26 },
{ name:"Himalayan Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5himalaw.webp", rtp:15 },
{ name:"Lucky Fishing", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysluckyfish.png", rtp:33 },
{ name:"Running Sushi", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscashconv.webp", rtp:41 },
{ name:"Joker Race", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25jokrace.png", rtp:55 },
{ name:"Candy Stars", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysstrwild.png", rtp:67 },
{ name:"Floating Dragon Hold & Spin Mega", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfltdrg.png", rtp:93 },
{ name:"Big Bass Day At The Races", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbbnz.png", rtp:85 },
{ name:"Big Juan", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40bigjuan.png", rtp:79 },
{ name:"Wild Wild Joker", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswwjoker.webp", rtp:81 },
{ name:"Big Bass Hold & Spinner Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbbhas.png", rtp:85 },
{ name:"Star Bounty", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayshive.png", rtp:26 },
{ name:"Tree Of Riches", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1fortunetree.png", rtp:15 },
{ name:"Barnyard Megahays Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmegahays.png", rtp:33 },
{ name:"Shield Of Sparta", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sparta.png", rtp:41 },
{ name:"Eye Of The Storm", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10eyestorm.png", rtp:55 },
{ name:"Yum Yum Powerways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysyumyum.png", rtp:67 },
{ name:"Super 7s", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5super7.png", rtp:93 },
{ name:"Year Of The Dragon King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20yotdk.webp", rtp:85 },
{ name:"John Hunter And Galileo’s Secrets", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10booklight.webp", rtp:79 },
{ name:"Kraken & s Sky Bounty", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50jucier.png", rtp:81 },
{ name:"Wild Beach Party", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bchprty.png", rtp:85 },
{ name:"888 Bonanza™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243goldfor.png", rtp:26 },
{ name:"Nile Fortunes™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20nilefort.png", rtp:15 },
{ name:"Spartan King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40spartaking.png", rtp:33 },
{ name:"Black Bull", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20trswild2.png", rtp:41 },
{ name:"Chilli Heat Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayschilheat.png", rtp:55 },
{ name:"Monkey Madness", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9madmonkey.png", rtp:67 },
{ name:"Holiday Ride", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25holiday.png", rtp:93 },
{ name:"Curse Of Werewolf Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswerewolf.png", rtp:85 },
{ name:"Caishen & s Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243fortune.png", rtp:79 },
{ name:"Queenie", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243queenie.png", rtp:81 },
{ name:"Shining Hot 100", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs100sh.png", rtp:85 },
{ name:"Book Of Fallen", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bookfallen.png", rtp:26 },
{ name:"Magician & s Secrets™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs4096magician.png", rtp:15 },
{ name:"Medusa & s Stone", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20medusast.webp", rtp:33 },
{ name:"Piggy Bank Bills", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9piggybank.png", rtp:41 },
{ name:"Rainbow Reels™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40rainbowr.png", rtp:55 },
{ name:"Infective Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40infwild.webp", rtp:67 },
{ name:"Dance Party", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243dancingpar.png", rtp:93 },
{ name:"Mystery Mice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20powerwild.webp", rtp:85 },
{ name:"Cash Box", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20cashmachine.png", rtp:79 },
{ name:"The Wild Machine", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40madwheel.png", rtp:81 },
{ name:"Ripe Rewards", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40stckwldlvl.webp", rtp:85 },
{ name:"8 Golden Dragon Challenge™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10gdchalleng.png", rtp:26 },
{ name:"Irish Crown", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20irishcrown.webp", rtp:15 },
{ name:"Little Gem Hold And Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5littlegem.png", rtp:33 },
{ name:"Ultra Burn", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5ultrab.png", rtp:41 },
{ name:"Zombie Carnival", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayszombcarn.png", rtp:55 },
{ name:"John Hunter And The Mayan Gods", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10mayangods.png", rtp:67 },
{ name:"Oodles Of Noodles", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10noodles.webp", rtp:93 },
{ name:"Gravity Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gravity.webp", rtp:85 },
{ name:"Badge Blitz", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25badge.webp", rtp:79 },
{ name:"Spellbinding Mystery", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20splmystery.png", rtp:81 },
{ name:"Congo Cash", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs432congocash.png", rtp:85 },
{ name:"The Money Men Megaways™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmoneyman.png", rtp:26 },
{ name:"Spirit Of Adventure", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10spiritadv.png", rtp:15 },
{ name:"Peak Power", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10powerlines.png", rtp:33 },
{ name:"Bomb Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25bomb.png", rtp:41 },
{ name:"Hot To Burn", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5hotburn.png", rtp:55 },
{ name:"Fu Fu Fu", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1fufufu.png", rtp:67 },
{ name:"Lady Godiva", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20godiva.png", rtp:93 },
{ name:"Ancient Egypt Classic", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10egyptcls.png", rtp:85 },
{ name:"Diamond Cascade™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50dmdcascade.png", rtp:79 },
{ name:"Fangtastic Freespins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fangfree.webp", rtp:81 },
{ name:"Robber Strike", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs4096robber.png", rtp:85 },
{ name:"Three Star Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10threestar.png", rtp:26 },
{ name:"Lucky New Year", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25newyear.png", rtp:15 },
{ name:"Gold Train", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs3train.png", rtp:33 },
{ name:"Queen Of Gods", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10egrich.png", rtp:41 },
{ name:"Triple Dragons", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5trdragons.png", rtp:55 },
{ name:"Wolf Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25wolfgold.png", rtp:67 },
{ name:"Wild Hop & Drop", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mparty.png", rtp:93 },
{ name:"Tic Tac Take", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10tictac.png", rtp:85 },
{ name:"Heroic Spins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20shootstars.jpg", rtp:79 },
{ name:"3 Kingdoms - Battle Of Red Cliffs", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25kingdoms.png", rtp:81 },
{ name:"The Dragon Tiger", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024dtiger.png", rtp:85 },
{ name:"Rise Of Samurai", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25samurai.png", rtp:26 },
{ name:"Journey To The West", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25journey.png", rtp:15 },
{ name:"The Tiger Warrior", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25tigerwar.png", rtp:33 },
{ name:"Super Joker", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5spjoker.png", rtp:41 },
{ name:"Beware The Deep Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbewaretd.png", rtp:55 },
{ name:"Wild Booster", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wildboost.png", rtp:67 },
{ name:"Striking Hot 5", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5strh.png", rtp:93 },
{ name:"Madame Destiny", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10madame.png", rtp:85 },
{ name:"Cash Elevator", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20terrorv.png", rtp:79 },
{ name:"Koi Pond", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243koipond.png", rtp:81 },
{ name:"Gem Elevator", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20elevclust.webp", rtp:85 },
{ name:"Release The Bison", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bison.png", rtp:26 },
{ name:"Treasure Horse", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs18mashang.png", rtp:15 },
{ name:"Mystery Of The Orient", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmorient.png", rtp:33 },
{ name:"Eye Of Cleopatra", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40cleoeye.png", rtp:41 },
{ name:"Cash Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbankbonz.png", rtp:55 },
{ name:"Pirate Gold Deluxe", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40pirgold.png", rtp:67 },
{ name:"Forging Wilds", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20forgewilds.webp", rtp:93 },
{ name:"Raging Bull", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243chargebull.png", rtp:85 },
{ name:"Dwarf & Dragon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysspltsym.jpg", rtp:79 },
{ name:"Secret City Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25spgldways.png", rtp:81 },
{ name:"Diamonds Of Egypt", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayseternity.png", rtp:85 },
{ name:"Magic Money Maze", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10mmm.png", rtp:26 },
{ name:"Jackpot Hunter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20jhunter.webp", rtp:15 },
{ name:"Piggy Bankers™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20piggybank.png", rtp:33 },
{ name:"Book Of Golden Sands", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbook.png", rtp:41 },
{ name:"Fat Panda", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20beefed.png", rtp:55 },
{ name:"Devilicious", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20devilic.jpg", rtp:67 },
{ name:"Pinup Girls", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20ltng.png", rtp:93 },
{ name:"Dynamite Diggin Doug", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10dyndigd.webp", rtp:85 },
{ name:"Frogs & Bugs", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfrbugs.png", rtp:79 },
{ name:"Spin & Score Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfrywld.png", rtp:81 },
{ name:"Blade & Fangs", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mergedwndw.png", rtp:85 },
{ name:"Floating Dragon New Year Festival Ul", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfltdrgny.webp", rtp:26 },
{ name:"Egyptian Fortunes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20egypttrs.png", rtp:15 },
{ name:"Knight Hot Spotz", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25spotz.png", rtp:33 },
{ name:"Pirates Pub", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9outlaw.png", rtp:41 },
{ name:"Dragon Hot Hold And Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5drhs.png", rtp:55 },
{ name:"Asgard", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25asgard.png", rtp:67 },
{ name:"Fire Archer", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25archer.png", rtp:93 },
{ name:"Lucky, Grace & Charm", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10luckcharm.png", rtp:85 },
{ name:"North Guardians", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50northgard.png", rtp:79 },
{ name:"Diamonds Are Forever 3 Lines", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/cs3w.png", rtp:81 },
{ name:"Lamp Of Infinity", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lampinf.png", rtp:85 },
{ name:"Dragon Ball", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1ball.png", rtp:26 },
{ name:"Magic Journey", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs8magicjourn.png", rtp:15 },
{ name:"Fishin &  Reels", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10goldfish.png", rtp:33 },
{ name:"Hot To Burn Multiplier", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5hotbmult.webp", rtp:41 },
{ name:"Dragon Kingdom - Eyes Of Fire", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5drmystery.png", rtp:55 },
{ name:"Joker King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25jokerking.png", rtp:67 },
{ name:"Pixie Wings", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50pixie.png", rtp:93 },
{ name:"Wild Depths", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40wanderw.png", rtp:85 },
{ name:"Down The Rails", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20underground.png", rtp:79 },
{ name:"Rainbow Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20rainbowg.png", rtp:81 },
{ name:"Pot Of Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20stckwldsc.jpg", rtp:85 },
{ name:"Strawberry Cocktail", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10strawberry.png", rtp:26 },
{ name:"Book Of Kingdoms", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25bkofkngdm.png", rtp:15 },
{ name:"Cash Chips™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20maskgame.png", rtp:33 },
{ name:"John Hunter And The Aztec Treasure", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7776secrets.png", rtp:41 },
{ name:"Timber Stacks™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaystimber.png", rtp:55 },
{ name:"Snakes And Ladders Megadice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10snakeladd.png", rtp:67 },
{ name:"Honey Honey Honey", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20honey.png", rtp:93 },
{ name:"Crank It Up", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20crankit.webp", rtp:85 },
{ name:"Fish Eye", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fisheye.png", rtp:79 },
{ name:"Fire Hot 20", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fh.png", rtp:81 },
{ name:"Hercules Son Of Zeus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50hercules.png", rtp:85 },
{ name:"Vampires Vs Wolves", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10vampwolf.png", rtp:26 },
{ name:"Hot To Burn 7 Deadly Free Spins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10hottb7fs.webp", rtp:15 },
{ name:"Hot Safari", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25safari.png", rtp:33 },
{ name:"Fonzo’s Feline Fortunes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fonzofff.webp", rtp:41 },
{ name:"Jasmine Dreams", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mvwild.png", rtp:55 },
{ name:"Wild Pixies", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wildpix.png", rtp:67 },
{ name:"Chase For Glory™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscfglory.png", rtp:93 },
{ name:"7 Piggies", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7pigs.png", rtp:85 },
{ name:"Jungle Gorilla", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gorilla.png", rtp:79 },
{ name:"Peking Luck", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25peking.png", rtp:81 },
{ name:"Pub Kings™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lvlup.png", rtp:85 },
{ name:"Day Of Dead", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20daydead.png", rtp:26 },
{ name:"Mighty Kong", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50kingkong.png", rtp:15 },
{ name:"Wild Wild Bananas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswwhex.png", rtp:33 },
{ name:"Legend Of Heroes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayslofhero.png", rtp:41 },
{ name:"Star Pirates Code", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10starpirate.png", rtp:55 },
{ name:"Mysterious", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs4096mystery.png", rtp:67 },
{ name:"Excalibur Unleashed", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20excalibur.png", rtp:93 },
{ name:"Hot Chilli", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs9hotroll.png", rtp:85 },
{ name:"Kingdom Of The Dead", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10kingofdth.png", rtp:79 },
{ name:"Book Of Aztec King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bookazteck.png", rtp:81 },
{ name:"Bull Fiesta", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25bullfiesta.png", rtp:85 },
{ name:"Cheeky Emperor", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243ckemp.png", rtp:26 },
{ name:"Gorilla Mayhem", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024gmayhem.png", rtp:15 },
{ name:"John Hunter And The Book Of Tutv", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaystut.png", rtp:33 },
{ name:"Crown Of Fire", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10crownfire.png", rtp:41 },
{ name:"Lobster Bob’s Sea Food And Win It", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lobseafd.jpg", rtp:55 },
{ name:"Fruit Rainbow", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40frrainbow.png", rtp:67 },
{ name:"Starz Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs117649starz.png", rtp:93 },
{ name:"The Great Stick-up", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20stickysymbol.png", rtp:85 },
{ name:"Fire Hot 100", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs100firehot.png", rtp:79 },
{ name:"Might Of Ra", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50mightra.png", rtp:81 },
{ name:"Fire Hot 40", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40firehot.png", rtp:85 },
{ name:"Smugglers Cove", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20smugcove.png", rtp:26 },
{ name:"Fire Hot 5", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5firehot.png", rtp:15 },
{ name:"Gold Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25goldrush.png", rtp:33 },
{ name:"The Alter Ego", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysalterego.png", rtp:41 },
{ name:"The Knight King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sknights.png", rtp:55 },
{ name:"Wild Walker", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25walker.png", rtp:67 },
{ name:"Castle Of Fire", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysexpandng.webp", rtp:93 },
{ name:"Shining Hot 5", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5sh.png", rtp:85 },
{ name:"Santa", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20santa.png", rtp:79 },
{ name:"Mystic Chief", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswest.png", rtp:81 },
{ name:"The Great Chicken Escape", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20chicken.png", rtp:85 },
{ name:"Ding Dong Christmas Bells™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10ddcbells.png", rtp:26 },
{ name:"Leprechaun Song", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20leprechaun.png", rtp:15 },
{ name:"Jade Butterfly", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024butterfly.png", rtp:33 },
{ name:"Jane Hunter And The Mask Of Montezum", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10jnmntzma.png", rtp:41 },
{ name:"Voodoo Magic", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40voodoo.png", rtp:55 },
{ name:"Return Of The Dead", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10returndead.png", rtp:67 },
{ name:"Escape The Pyramid - Fire & Ice<", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fireice.webp", rtp:93 },
{ name:"Tundra’s Fortune™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysraghex.png", rtp:85 },
{ name:"Safari King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50safariking.png", rtp:79 },
{ name:"Ice Lobster", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20stickypos.png", rtp:81 },
{ name:"Great Lagoon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25lagoon.png", rtp:85 },
{ name:"Hellvis Wild", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243nudge4gold.png", rtp:26 },
{ name:"Irish Charms", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/cs3irishcharms.png", rtp:15 },
{ name:"Gems Of Serengeti", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lcount.png", rtp:33 },
{ name:"Snakes & Ladders 2 - Snake Eyes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10snakeeyes.png", rtp:41 },
{ name:"Devil & s 13", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs13g.png", rtp:55 },
{ name:"Congo Cash Xl", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayscongcash.webp", rtp:67 },
{ name:"Frozen Tropics", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysftropics.webp", rtp:93 },
{ name:"Disco Lady", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs243discolady.png", rtp:85 },
{ name:"Fairytale Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15fairytale.png", rtp:79 },
{ name:"Hockey Attack", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs88hockattack.png", rtp:81 },
{ name:"Demon Pots", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40demonpots.png", rtp:85 },
{ name:"3 Genie Wishes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50aladdin.png", rtp:26 },
{ name:"Lobster Bob & s Crazy Crab Shack<", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lobcrab.png", rtp:15 },
{ name:"7 Monkeys", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7monkeys.png", rtp:33 },
{ name:"Lucky Dragons", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs50chinesecharms.png", rtp:41 },
{ name:"Colossal Cash Zone", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20colcashzone.png", rtp:55 },
{ name:"Sea Fantasy™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysseastory.png", rtp:67 },
{ name:"Chicken Chase", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10chkchase.png", rtp:93 },
{ name:"Mighty Munching Melons", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mmmelon.png", rtp:85 },
{ name:"Pirate Golden Age", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mtreasure.png", rtp:79 },
{ name:"Vegas Nights", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25vegas.png", rtp:81 },
{ name:"Moonshot", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1024moonsh.png", rtp:85 },
{ name:"Shining Hot 40", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40sh.png", rtp:26 },
{ name:"Shining Hot 20", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sh.png", rtp:15 },
{ name:"Good Luck & Good Fortune", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10luckfort.webp", rtp:33 },
{ name:"Great Reef", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25sea.png", rtp:41 },
{ name:"Emerald King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20eking.png", rtp:55 },
{ name:"The Red Queen", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysredqueen.png", rtp:67 },
{ name:"The Ultimate 5", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20ultim5.png", rtp:93 },
{ name:"Street Racer", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40streetracer.png", rtp:85 },
{ name:"Mysterious Egypt", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10wildtut.png", rtp:79 },
{ name:"Da Vinci & s Treasure", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25davinci.png", rtp:81 },
{ name:"African Elephant", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20hotzone.png", rtp:85 },
{ name:"Hot To Burn Extreme", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40hotburnx.png", rtp:26 },
{ name:"Wild Gladiator", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25gladiator.png", rtp:15 },
{ name:"Ancient Egypt", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10egypt.png", rtp:33 },
{ name:"Odds On Winner", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10frontrun.jpg", rtp:41 },
{ name:"Leprechaun Carol", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20leprexmas.png", rtp:55 },
{ name:"Greedy Wolf", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20wolfie.png", rtp:67 },
{ name:"Penguins Christmas Party Time", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25xmasparty.webp", rtp:93 },
{ name:"Towering Fortunes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20theights.png", rtp:85 },
{ name:"Fury Of Odin Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfuryodin.png", rtp:79 },
{ name:"Gold Oasis", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysincwnd.webp", rtp:81 },
{ name:"Cyclops Smash™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20earthquake.png", rtp:85 },
{ name:"Loki’s Riches", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20loksriches.png", rtp:26 },
{ name:"Book Of Tut Respin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10tut.png", rtp:15 },
{ name:"Gears Of Horus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20clustext.png", rtp:33 },
{ name:"Hercules And Pegasus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20hercpeg.png", rtp:41 },
{ name:"Emerald King Rainbow Road", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20ekingrr.png", rtp:55 },
{ name:"Wolf Gold 4 Pack", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25quadwolf.webp", rtp:67 },
{ name:"Drill That Gold", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20drtgold.png", rtp:93 },
{ name:"Big Burger Load It Up With Xtra Chee", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bburger.webp", rtp:85 },
{ name:"Ancient Island Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysmodfr.webp", rtp:79 },
{ name:"Aladdin And The Sorcerer", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20aladdinsorc.png", rtp:81 },
{ name:"Yeti Quest", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mesmult.webp", rtp:85 },
{ name:"Wild Wild Pearls", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayspearls.webp", rtp:26 },
{ name:"Train To Seoul", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs15seoultrain.png", rtp:15 },
{ name:"Peppe’s Pepperoni Pizza Plaza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaystonypzz.webp", rtp:33 },
{ name:"Starlight Wins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayssw.webp", rtp:41 },
{ name:"Olympus Wins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysolwfp.webp", rtp:55 },
{ name:"Lucky Tiger 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckyt1kly.webp", rtp:67 },
{ name:"777 Rush", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5t8goldfp.webp", rtp:93 },
{ name:"Lucky Phoenix", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckyphnly.webp", rtp:85 },
{ name:"Lucky Tiger", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckytigly.webp", rtp:79 },
{ name:"Wealthy Frog", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5wfrog.webp", rtp:81 },
{ name:"Pig Farm", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25pfarmfp.webp", rtp:85 },
{ name:"Lucky Monkey", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckymly.webp", rtp:26 },
{ name:"Fortune Of Aztec", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysaztecgm.webp", rtp:15 },
{ name:"Lucky Ox", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10fortnhs.webp", rtp:33 },
{ name:"Code Of Cairo", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5spjokfp.webp", rtp:41 },
{ name:"Emotiwins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10emotiwins.webp", rtp:55 },
{ name:"Lucky Mouse", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10forwildly.webp", rtp:67 },
{ name:"Jelly Candy", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5jellyc.webp", rtp:93 },
{ name:"Plushie Wins", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1dragon888.webp", rtp:85 },
{ name:"Dino Drop", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5tdragresk.webp", rtp:79 },
{ name:"Lucky Dog", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckydogly.webp", rtp:81 },
{ name:"Master Gems", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs1mjokfp.webp", rtp:85 },
{ name:"Mpoplay Starlight Princess 1000v", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mpoplaystx.png", rtp:26 },
{ name:"Mpoplay Gates Of Gatot Kaca", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mpoplaygat.webp", rtp:15 },
{ name:"Mpoplay Sweet Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mpoplaybnz.webp", rtp:33 },
{ name:"Mpoplay Gates Of Olympus", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mpogates.webp", rtp:41 },
{ name:"Mpoplay Aztec Gems", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5aztecmpoplay.png", rtp:55 },
{ name:"Sugar Rush Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20sugardice.webp", rtp:67 },
{ name:"Hokkaido Wolf", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs576hokkwolf.png", rtp:93 },
{ name:"Aztec King Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysaztecking.png", rtp:85 },
{ name:"Joker Jewels Dice™", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5jokerdice.png", rtp:79 },
{ name:"Aztec King", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25aztecking.png", rtp:81 },
{ name:"Fortune Hit’n Roll", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40wildrun.webp", rtp:85 },
{ name:"Empty The Bank", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20emptybank.png", rtp:26 },
{ name:"Book Of Tut", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bookoftut.png", rtp:15 },
{ name:"Wolf Gold Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25wgdice.webp", rtp:33 },
{ name:"Bounty Hunter", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bhunter.webp", rtp:41 },
{ name:"Jackpot Blaze", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10jpblaze.webp", rtp:55 },
{ name:"Spire+", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/ar1spire.webp", rtp:67 },
{ name:"Argonauts", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysargonts.webp", rtp:93 },
{ name:"Hundreds And Thousands", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs100hsandks.webp", rtp:85 },
{ name:"Lucky Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckdce88.webp", rtp:79 },
{ name:"Mermaid’s Treasure Trove", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mmdtres.webp", rtp:81 },
{ name:"Chests Of Cai Shen 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs25caishen2.webp", rtp:85 },
{ name:"Zombie School Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayspompmr2.webp", rtp:26 },
{ name:"Fire Stampede 2", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysfirest2.webp", rtp:15 },
{ name:"Mystic Wishes", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs7fire88fp.webp", rtp:33 },
{ name:"Bigger Barn House Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysbbarnh.webp", rtp:41 },
{ name:"Captain Kraken Megaways", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayschilhtwo.webp", rtp:55 },
{ name:"Lobster House", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20lbstrhouse.webp", rtp:67 },
{ name:"Genie’s Gem Bonanza", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20gengembnz.webp", rtp:93 },
{ name:"Happy Nets", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20fishptrn.webp", rtp:85 },
{ name:"Bee Keeper", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10beekeep.webp", rtp:79 },
{ name:"Big Bass Halloween 3", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bhallbnza3.webp", rtp:81 },
{ name:"Big Bass Reel Repeat", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbrrp.webp", rtp:85 },
{ name:"Lava Balls", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayslavabls.webp", rtp:26 },
{ name:"Ultra Burn Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5ultradice.webp", rtp:15 },
{ name:"Ice Mints", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20popbottles.webp", rtp:33 },
{ name:"Spellmaster", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10spellmastr.webp", rtp:41 },
{ name:"Red Hot Luck", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20powerpays.webp", rtp:55 },
{ name:"Country Farming", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mysteryst.webp", rtp:67 },
{ name:"Happy Hooves", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40mstrwild.webp", rtp:93 },
{ name:"Saiyan Mania", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20saiman.webp", rtp:85 },
{ name:"Big Bass Dice", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbdice.webp", rtp:79 },
{ name:"Busy Bees", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20bl.png", rtp:81 },
{ name:"Mines+", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/ar1minehnt.webp", rtp:85 },
{ name:"Lucky Panda", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5lckpnd.webp", rtp:26 },
{ name:"Pandemic Rising", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40pdmrsg.webp", rtp:15 },
{ name:"Frightening Frankie", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20frankie.webp", rtp:33 },
{ name:"Bingo Mania", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs30bingomania.webp", rtp:41 },
{ name:"Mpoplay Sweet Bonanza Xmas", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20mposbxmas.webp", rtp:55 },
{ name:"Wild Wild Riches Returns", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswwrichr.webp", rtp:67 },
{ name:"Duel Of Night & Day", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysyinyang.webp", rtp:93 },
{ name:"Santa’s Slay", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10santasl.webp", rtp:85 },
{ name:"Bloody Dawn", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswayswildb.webp", rtp:79 },
{ name:"Hammerstorm", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs40hmrstrm.webp", rtp:81 },
{ name:"Big Bass Christmas – Frozen Lake", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbglxmas.webp", rtp:85 },
{ name:"Dj Neko", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10djneko.webp", rtp:26 },
{ name:"Super Gummy Strike", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5supergummy.webp", rtp:15 },
{ name:"Zeus Vs Typhon", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vswaysreelbtl.webp", rtp:33 },
{ name:"Sweet Craze", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs20chestcol.webp", rtp:41 },
{ name:"Lucky Fortune Tree", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5luckycol.webp", rtp:55 },
{ name:"Big Bass Splash 1000", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs10bbsplashx.webp", rtp:67 },
{ name:"Limbo+", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/ar1limboplus.webp", rtp:93 },
{ name:"Joker’s Jewels Hold & Spin", img:"https://images.linkcdn.cloud/global/game-list/slot/pragmaticplay/vs5jokjewhs.webp", rtp:85 }
];

const grid = document.getElementById("rtpGrid");

games.forEach(game => {
  let color = game.rtp >= 70 ? "green" : game.rtp >= 40 ? "yellow" : "red";

  grid.innerHTML += `
    <div class="game-card">
      <img src="${game.img}" alt="${game.name}">
      <div class="game-info">
        <strong>${game.name}</strong>
        <div class="progress">
          <span class="${color}" style="width:${game.rtp}%"></span>
        </div>
        <div class="percent">${game.rtp}%</div>
      </div>
    </div>
  `;
});
